#!/opt/homebrew/bin/uv run --script
# /// script
# dependencies = [
#   "neovim-remote",
#   "psutil",
#   "pyobjc-core",
#   "pyobjc-framework-Cocoa",
# ]
# ///

import configparser
import os
import pathlib
import subprocess

from AppKit import NSApplication, NSObject, NSApplicationActivationPolicyProhibited
from Cocoa import NSLog
from Foundation import NSDistributedNotificationCenter, NSUserDefaults
from PyObjCTools import AppHelper
from nvr.nvr import Nvr
import psutil

HOMEDIR = pathlib.Path(os.environ["HOME"])


def update_kitty(preset: str):
    subprocess.run(
        [
            "/opt/homebrew/bin/kitty",
            "+kitten",
            "themes",
            "--reload-in=all",
            "--config-file-name=themes.conf",
            preset,
        ]
    )

    NSLog(f"Changed kitty theme to preset={preset}")


def update_neovim(colorscheme: str, background: str):
    with open(HOMEDIR / ".local/state/nvim/theme", "w") as fp:
        fp.write(f"{colorscheme}\n{background}\n")

    servers: list[str] = []

    # Get a list of NeoVim servers
    # From: https://github.com/mhinz/neovim-remote/blob/1004d41696a3de12f0911b1949327c3dbe4a62ab/nvr/nvr.py#L370
    for proc in psutil.process_iter(attrs=["name"]):
        if proc.info["name"] != "nvim":
            continue

        try:
            for conn in proc.net_connections("inet4"):
                servers.insert(0, ":".join(map(str, conn.laddr)))
            for conn in proc.net_connections("inet6"):
                servers.insert(0, ":".join(map(str, conn.laddr)))
            for conn in proc.net_connections("unix"):
                if conn.laddr:
                    servers.insert(0, conn.laddr)
        except psutil.AccessDenied:
            continue

    for server in servers:
        nvr = Nvr(server)
        nvr.attach()
        if not nvr.server:
            NSLog(f"Failed to attach to {server}")

        nvr.execute(["+lua UpdateColorscheme()"])

        NSLog(f"Updated Neovim instance {server} to colorscheme={colorscheme} background={background}")


class AppDelegate(NSObject):
    def applicationDidFinishLaunching_(self, _):
        nc = NSDistributedNotificationCenter.defaultCenter()
        nc.addObserver_selector_name_object_(
            self, b"enableDarkMode:", "AppleInterfaceThemeChangedNotification", None
        )

    def enableDarkMode_(self, _):
        dark: bool = (
            NSUserDefaults.standardUserDefaults().stringForKey_("AppleInterfaceStyle")
            == "Dark"
        )

        config = configparser.ConfigParser()
        config.read(HOMEDIR / ".config/themeobserver/config.ini")
        proxy = config["dark" if dark else "light"]

        update_kitty(proxy.get("kitty-preset", "Default"))
        update_neovim(proxy.get("nvim-colorscheme", "default"),
                      proxy.get("nvim-background", "dark"))


app = NSApplication.sharedApplication()
app.replyToApplicationShouldTerminate_(True)
app.setActivationPolicy_(NSApplicationActivationPolicyProhibited)

appDelegate = AppDelegate.alloc().init()
app.setDelegate_(appDelegate)

NSLog("Listening for AppleInterfaceThemeChangedNotification events...")

# This must be a GUI app, as AppleInterfaceThemeChangedNotification is not sent to console apps
AppHelper.runEventLoop(installInterrupt=True)

# vim: set ft=python:
