WHEEL_UP ignore
WHEEL_DOWN ignore
WHEEL_LEFT ignore
WHEEL_RIGHT ignore
F show-text "estimated frame: ${estimated-frame-number}"

{ add speed -0.01
} add speed +0.01

[ multiply speed 0.943874312681693
] multiply speed 1.0594630943529535
